// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA35tH6Q7gVvdJLpnXMX1hN0wsUHf-BvN4',
    appId: '1:41235784406:web:aeaa672299c4dd77909f77',
    messagingSenderId: '41235784406',
    projectId: 'flutter-note-app-5b49c',
    authDomain: 'flutter-note-app-5b49c.firebaseapp.com',
    databaseURL: 'https://flutter-note-app-5b49c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-note-app-5b49c.firebasestorage.app',
    measurementId: 'G-QFKVGMZ062',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5Ax5f_W4pBwiuWTMbXHJODdhW_lnJEM0',
    appId: '1:41235784406:android:39676e97d7759de6909f77',
    messagingSenderId: '41235784406',
    projectId: 'flutter-note-app-5b49c',
    databaseURL: 'https://flutter-note-app-5b49c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-note-app-5b49c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3BwR7X2Xt9keb8bjGeXPK-7uuz0uwVCw',
    appId: '1:41235784406:ios:49a02778a0263668909f77',
    messagingSenderId: '41235784406',
    projectId: 'flutter-note-app-5b49c',
    databaseURL: 'https://flutter-note-app-5b49c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-note-app-5b49c.firebasestorage.app',
    iosBundleId: 'com.example.examReviewer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3BwR7X2Xt9keb8bjGeXPK-7uuz0uwVCw',
    appId: '1:41235784406:ios:49a02778a0263668909f77',
    messagingSenderId: '41235784406',
    projectId: 'flutter-note-app-5b49c',
    databaseURL: 'https://flutter-note-app-5b49c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-note-app-5b49c.firebasestorage.app',
    iosBundleId: 'com.example.examReviewer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA35tH6Q7gVvdJLpnXMX1hN0wsUHf-BvN4',
    appId: '1:41235784406:web:631d396907d5f8e4909f77',
    messagingSenderId: '41235784406',
    projectId: 'flutter-note-app-5b49c',
    authDomain: 'flutter-note-app-5b49c.firebaseapp.com',
    databaseURL: 'https://flutter-note-app-5b49c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-note-app-5b49c.firebasestorage.app',
    measurementId: 'G-JPBNCCLF7Q',
  );

}